### ISSUE TITLE
Error in Snipsfile documentation

### ISSUE THREAD

**Issue by noli2000** [snipsco/snips-skill-owm#9]
Hi there,
the Readme says that this should added to the Snipsfile :
```
skills:
- package_name: snipsowm
  class_name: SnipsOWM
  pip: snipsowm
  default_location: "Paris,fr"
  params:
    - api_key: <YOUR API KEY>
      locale: en_US
      default_location: France
```
But th "-" before api_key generates an error when installing the skill :
```
pi@snips:~/.snips $ snipsmanager install skills
❯ Installing skills
✘ 'list' object has no attribute 'items'
```
Could you please correct that ?
